language: node_js
node_js:
  - "8"
  - "10"
  - "12"
  - "14"
  - "16"
addons:
  chrome: stable
sudo: required
before_script:
  - "sudo chown root /opt/google/chrome/chrome-sandbox"
  - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"